### ISSUE TITLE
Add api endpoints for tutors

### ISSUE THREAD

**Issue by johnkuefler** [johnkuefler/TutorTime#10]

**Comment by chrisevans9629** [comment]
## Documentation
[Setup Controller](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#add-a-controller)

## Minimal End Points needed

- GET /Tutor/ **gets all the tutors**
- GET /Tutor/id **gets a tutor with id**

- GET /Tutor/id/Requests **gets the tutor's requests**
- POST /TutorRequest/ **adds a tutor session**
- PUT /TutorRequest/id/Join **increments the session number of people count**

**Comment by johnkuefler** [comment]
@chrisevans9629 I believe the last two items would apply to task #12, rather than this one.

**Comment by chrisevans9629** [comment]
@johnkuefler  yes I agree I forgot about that.  I was just about to reference the other issue.
