### ISSUE TITLE
Make navbar match mockup

### ISSUE THREAD

**Issue by johnkuefler** [johnkuefler/TutorTime#13]
Add logo and links to navbar. It will be in the Views/Shared/_Layout.cshtml file

**Comment by aubristahl** [comment]
@Lydia-Winters could I have the logo please? :)

**Comment by Lydia-Winters** [comment]
@aubristahl I can send it tomorrow afternoon it's on my work computer.

**Comment by johnkuefler** [comment]
![tutor-time](https://user-images.githubusercontent.com/13266355/64214228-34922800-ce75-11e9-9783-3072c92f9dff.png)

@aubristahl @Lydia-Winters  I was able to grab this out of the XD Lydia sent me - it's not super high res but should be ok for the navbar!

**Comment by johnkuefler** [comment]
Fixed in PR #32
