### ISSUE TITLE
Add button for creating new request

### ISSUE THREAD

**Issue by chrisevans9629** [johnkuefler/TutorTime#57]
Need to add the button to create a new session:
![image](https://user-images.githubusercontent.com/33850520/64893672-45912500-d63d-11e9-9f2e-d4f5fa7c8794.png)

I'm guessing this would be done through a modal dialog or something like that?

**Comment by johnkuefler** [comment]
Yes we will use a modal for that. That will be the only thing left needed to complete the app - so we can probably tackle that at our last meeting.

**Comment by johnkuefler** [comment]
@chrisevans9629  If you want to give it a try beforehand  as a learning exercise, this is the modal component we'd probably use https://www.npmjs.com/package/vue-js-modal

**Comment by chrisevans9629** [comment]
@johnkuefler yeah I can give it a try.  It'd be good practice
